counter/urls.py
from django.urls import path
from . import views

app_name = "counter"

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path("email_request/", views.SignUp.as_view(), name= "email_request"),
    path("email_request/thanks/", views.ThanksPage.as_view(), name= "thanks"),
]

website_corona/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('counter.urls')),
    path('admin/', admin.site.urls),
]

counter/models.py
from django.db import models
from django.core.mail import send_mail

class Subscriber(models.Model):

    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True, error_messages={'unique': "This email is already registered."})

    #     Email sending

    def save(self, *args, **kwargs):
        if not self.pk:
            send_mail(
                'Thanks for suscribing ' + self.name,
                'Here is the message.',
                'patojezkopotocny@gmail.com',
                [self.email],
                fail_silently=False,
            )
        return super(Subscriber, self).save(*args, **kwargs)

    def __str__(self):
        return self.email

counter/forms.py
from django import forms
from counter.models import Subscriber



class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = '__all__'

counter/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from counter.forms import SubscriberForm
from counter.models import Subscriber

from counter import w_scrape_script



class HomePage(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['tested'] = w_scrape_script.tested
        context['confirmed'] = w_scrape_script.confirmed
        context['confirmed_today'] = w_scrape_script.confirmed_today
        context['deaths'] = w_scrape_script.deaths
        context['cured'] = w_scrape_script.cured
        return context


class SignUp(CreateView):
    model = Subscriber
    fields = ('name', 'email')
    template_name = 'accounts/signup.html'
    success_url = 'thanks/'


class ThanksPage(TemplateView):
    template_name = 'accounts/thanks.html'

templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h2>Signup</h2>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/accounts/thanks.html
{% extends "base.html" %}

{% block content %}
<h1>Thanks for subscribing!</h1>
{% endblock %}

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html>

<head>
  <title>Corona Virus</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}" />
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="{% url 'counter:home_page' %}">Corona<span class="logo_colour"> Virus Live Info</span></a></h1>
          <h2>Keep track of what matters.</h2>
        </div>
      </div>

    </div>
    <div id="site_content">
      <div class="sidebar">
        {% block sidebar %}

        {% endblock %}
      </div>
      <div id="content">
        {% block content %}

        {% endblock %}
      </div>
    </div>
    <div id="footer">
      <p>Copyright &copy; night_sky | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">design from HTML5webtemplates.co.uk</a></p>
    </div>
  </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block sidebar %}
<h1><a href="{% url 'counter:email_request' %}">Subscribe</a></h1>
{% endblock %}

{% block content %}
  <h1>Current Statictics:</h1>
          <h3>Tested: {{ tested }}</h3>
          <h3>Confirmed: {{ confirmed }}</h3>
          <h3>Confirmed today: {{ confirmed_today }}</h3>
          <h3>Deaths: {{ deaths }}</h3>
          <h3>Cured: {{ cured }}</h3>
{% endblock %}